export type Candidate = {
  id: string;
  name: string;
  role: string;
  skills: string[];
  interests: string[];
  availability: string;
  experience: "Junior" | "Mid" | "Senior" | "Lead";
  bio: string;
  avatarUrl: string;
  location: string;
  email: string;
  phone: string;
  linkedinHandle: string;
  githubHandle?: string;
};

export const candidates: Candidate[] = [
  {
    id: "c01",
    name: "Maya Chen",
    role: "Full-Stack Engineer",
    skills: ["React", "Node.js", "TypeScript", "PostgreSQL", "GraphQL"],
    interests: ["fintech", "developer tools", "open source"],
    availability: "full-time",
    experience: "Senior",
    bio: "Ships end-to-end features fast and cares deeply about DX.",
    avatarUrl: "https://randomuser.me/api/portraits/women/65.jpg",
    location: "Austin, TX",
    email: "maya.chen@projectmatch.dev",
    phone: "+1 (555) 018-2231",
    linkedinHandle: "mayachen",
    githubHandle: "mchen-dev",
  },
  {
    id: "c02",
    name: "Diego Ramirez",
    role: "ML Engineer",
    skills: ["Python", "PyTorch", "LLMs", "RAG pipelines", "MLOps"],
    interests: ["healthtech", "NLP", "climate"],
    availability: "20hrs/wk",
    experience: "Mid",
    bio: "Turns fuzzy research ideas into shippable model pipelines.",
    avatarUrl: "https://randomuser.me/api/portraits/men/32.jpg",
    location: "Mexico City, MX",
    email: "diego.ramirez@projectmatch.dev",
    phone: "+1 (555) 018-4471",
    linkedinHandle: "diegoramirez",
    githubHandle: "dramirez-ml",
  },
  {
    id: "c03",
    name: "Priya Sharma",
    role: "Product Designer",
    skills: ["Figma", "UX research", "Design systems", "Prototyping"],
    interests: ["accessibility", "consumer apps", "education"],
    availability: "full-time",
    experience: "Senior",
    bio: "Obsesses over the small interactions that make products feel alive.",
    avatarUrl: "https://randomuser.me/api/portraits/women/68.jpg",
    location: "Bengaluru, IN",
    email: "priya.sharma@projectmatch.dev",
    phone: "+1 (555) 018-7723",
    linkedinHandle: "priyasharma",
  },
  {
    id: "c04",
    name: "Jordan Lee",
    role: "Backend Engineer",
    skills: ["Go", "Distributed systems", "Kafka", "Kubernetes", "AWS"],
    interests: ["infra", "scalability", "devtools"],
    availability: "full-time",
    experience: "Lead",
    bio: "Designs systems that stay boring under 10x load.",
    avatarUrl: "https://randomuser.me/api/portraits/men/12.jpg",
    location: "Seattle, WA",
    email: "jordan.lee@projectmatch.dev",
    phone: "+1 (555) 018-9012",
    linkedinHandle: "jordanlee",
    githubHandle: "jlee-systems",
  },
  {
    id: "c05",
    name: "Amara Okafor",
    role: "Growth Marketer",
    skills: ["SEO", "Lifecycle marketing", "A/B testing", "Analytics", "Copywriting"],
    interests: ["consumer growth", "creator economy", "storytelling"],
    availability: "10hrs/wk",
    experience: "Mid",
    bio: "Finds the channel nobody else was looking at.",
    avatarUrl: "https://randomuser.me/api/portraits/women/21.jpg",
    location: "Lagos, NG",
    email: "amara.okafor@projectmatch.dev",
    phone: "+1 (555) 018-3345",
    linkedinHandle: "amaraokafor",
  },
  {
    id: "c06",
    name: "Ken Watanabe",
    role: "Mobile Engineer",
    skills: ["Swift", "Kotlin", "React Native", "Mobile performance"],
    interests: ["health & fitness", "gaming", "AR"],
    availability: "full-time",
    experience: "Senior",
    bio: "Native-first mindset, ships polished mobile experiences.",
    avatarUrl: "https://randomuser.me/api/portraits/men/54.jpg",
    location: "Tokyo, JP",
    email: "ken.watanabe@projectmatch.dev",
    phone: "+1 (555) 018-5589",
    linkedinHandle: "kenwatanabe",
    githubHandle: "kwatanabe-mobile",
  },
  {
    id: "c07",
    name: "Sofia Petrova",
    role: "Data Scientist",
    skills: ["Python", "SQL", "Statistics", "Experimentation", "dbt"],
    interests: ["marketplaces", "pricing", "behavioral economics"],
    availability: "20hrs/wk",
    experience: "Mid",
    bio: "Turns messy data into decisions people actually trust.",
    avatarUrl: "https://randomuser.me/api/portraits/women/33.jpg",
    location: "Warsaw, PL",
    email: "sofia.petrova@projectmatch.dev",
    phone: "+1 (555) 018-6612",
    linkedinHandle: "sofiapetrova",
    githubHandle: "spetrova-data",
  },
  {
    id: "c08",
    name: "Marcus Bell",
    role: "Product Manager",
    skills: ["Roadmapping", "User research", "Agile", "Stakeholder alignment"],
    interests: ["B2B SaaS", "productivity tools", "AI products"],
    availability: "full-time",
    experience: "Senior",
    bio: "Cuts scope ruthlessly to protect what actually matters.",
    avatarUrl: "https://randomuser.me/api/portraits/men/76.jpg",
    location: "Chicago, IL",
    email: "marcus.bell@projectmatch.dev",
    phone: "+1 (555) 018-1147",
    linkedinHandle: "marcusbell",
  },
  {
    id: "c09",
    name: "Nina Kowalski",
    role: "Frontend Engineer",
    skills: ["React", "Next.js", "Framer Motion", "CSS", "Accessibility"],
    interests: ["design engineering", "animation", "design systems"],
    availability: "full-time",
    experience: "Mid",
    bio: "Bridges design and code — pixel-perfect and buttery smooth.",
    avatarUrl: "https://randomuser.me/api/portraits/women/12.jpg",
    location: "Krakow, PL",
    email: "nina.kowalski@projectmatch.dev",
    phone: "+1 (555) 018-2298",
    linkedinHandle: "ninakowalski",
    githubHandle: "nkowalski-fe",
  },
  {
    id: "c10",
    name: "Ravi Menon",
    role: "DevOps / SRE",
    skills: ["Terraform", "AWS", "CI/CD", "Observability", "Docker"],
    interests: ["reliability", "cost optimization", "security"],
    availability: "20hrs/wk",
    experience: "Senior",
    bio: "Makes deploys boring and incidents rare.",
    avatarUrl: "https://randomuser.me/api/portraits/men/41.jpg",
    location: "Pune, IN",
    email: "ravi.menon@projectmatch.dev",
    phone: "+1 (555) 018-8834",
    linkedinHandle: "ravimenon",
    githubHandle: "rmenon-ops",
  },
  {
    id: "c11",
    name: "Elena Vasquez",
    role: "UX Researcher",
    skills: ["User interviews", "Usability testing", "Survey design", "Synthesis"],
    interests: ["healthtech", "fintech", "inclusive design"],
    availability: "10hrs/wk",
    experience: "Mid",
    bio: "Gets to the real problem before anyone writes a line of code.",
    avatarUrl: "https://randomuser.me/api/portraits/women/50.jpg",
    location: "Madrid, ES",
    email: "elena.vasquez@projectmatch.dev",
    phone: "+1 (555) 018-4456",
    linkedinHandle: "elenavasquez",
  },
  {
    id: "c12",
    name: "Tom Fischer",
    role: "Security Engineer",
    skills: ["AppSec", "Penetration testing", "Auth systems", "Threat modeling"],
    interests: ["fintech", "privacy", "compliance"],
    availability: "10hrs/wk",
    experience: "Senior",
    bio: "Thinks like an attacker so the team doesn't have to.",
    avatarUrl: "https://randomuser.me/api/portraits/men/23.jpg",
    location: "Berlin, DE",
    email: "tom.fischer@projectmatch.dev",
    phone: "+1 (555) 018-9967",
    linkedinHandle: "tomfischer",
    githubHandle: "tfischer-sec",
  },
  {
    id: "c13",
    name: "Yuki Tanaka",
    role: "Game Developer",
    skills: ["Unity", "C#", "3D graphics", "Physics engines"],
    interests: ["gaming", "AR/VR", "interactive media"],
    availability: "full-time",
    experience: "Mid",
    bio: "Builds worlds people don't want to leave.",
    avatarUrl: "https://randomuser.me/api/portraits/women/26.jpg",
    location: "Osaka, JP",
    email: "yuki.tanaka@projectmatch.dev",
    phone: "+1 (555) 018-3391",
    linkedinHandle: "yukitanaka",
    githubHandle: "ytanaka-game",
  },
  {
    id: "c14",
    name: "Grace Kim",
    role: "ML Engineer",
    skills: ["Computer vision", "TensorFlow", "Edge deployment", "Python"],
    interests: ["robotics", "climate", "agritech"],
    availability: "full-time",
    experience: "Senior",
    bio: "Gets models running fast on hardware that shouldn't be able to run them.",
    avatarUrl: "https://randomuser.me/api/portraits/women/79.jpg",
    location: "Seoul, KR",
    email: "grace.kim@projectmatch.dev",
    phone: "+1 (555) 018-6675",
    linkedinHandle: "gracekim",
    githubHandle: "gkim-cv",
  },
  {
    id: "c15",
    name: "Liam O'Brien",
    role: "Founding Engineer",
    skills: ["TypeScript", "System design", "Product sense", "Rapid prototyping"],
    interests: ["0-to-1 products", "developer tools", "AI"],
    availability: "full-time",
    experience: "Lead",
    bio: "Thrives in ambiguity, ships MVPs in days not weeks.",
    avatarUrl: "https://randomuser.me/api/portraits/men/8.jpg",
    location: "Dublin, IE",
    email: "liam.obrien@projectmatch.dev",
    phone: "+1 (555) 018-7789",
    linkedinHandle: "liamobrien",
    githubHandle: "lobrien-eng",
  },
  {
    id: "c16",
    name: "Fatima Al-Sayed",
    role: "Data Engineer",
    skills: ["Airflow", "Spark", "SQL", "Data warehousing", "Python"],
    interests: ["analytics infra", "fintech", "logistics"],
    availability: "20hrs/wk",
    experience: "Mid",
    bio: "Builds pipelines that don't page anyone at 3am.",
    avatarUrl: "https://randomuser.me/api/portraits/women/56.jpg",
    location: "Dubai, AE",
    email: "fatima.alsayed@projectmatch.dev",
    phone: "+1 (555) 018-2214",
    linkedinHandle: "fatimaalsayed",
    githubHandle: "falsayed-data",
  },
  {
    id: "c17",
    name: "Oscar Lindqvist",
    role: "Brand & Visual Designer",
    skills: ["Illustration", "Motion design", "Branding", "Adobe Creative Suite"],
    interests: ["consumer brands", "storytelling", "media"],
    availability: "10hrs/wk",
    experience: "Mid",
    bio: "Gives products a personality worth remembering.",
    avatarUrl: "https://randomuser.me/api/portraits/men/61.jpg",
    location: "Stockholm, SE",
    email: "oscar.lindqvist@projectmatch.dev",
    phone: "+1 (555) 018-5523",
    linkedinHandle: "oscarlindqvist",
  },
  {
    id: "c18",
    name: "Hannah Weiss",
    role: "Customer & Community Lead",
    skills: ["Community building", "Support ops", "Onboarding", "Content"],
    interests: ["creator tools", "education", "open source"],
    availability: "20hrs/wk",
    experience: "Junior",
    bio: "Turns first-time users into your loudest advocates.",
    avatarUrl: "https://randomuser.me/api/portraits/women/9.jpg",
    location: "Toronto, CA",
    email: "hannah.weiss@projectmatch.dev",
    phone: "+1 (555) 018-8856",
    linkedinHandle: "hannahweiss",
  },
  {
    id: "c19",
    name: "Carlos Mendez",
    role: "Full-Stack Engineer",
    skills: ["Vue.js", "Django", "MongoDB", "Redis", "Docker"],
    interests: ["marketplaces", "logistics", "open source"],
    availability: "full-time",
    experience: "Mid",
    bio: "Comfortable owning a feature from database schema to pixel-perfect UI.",
    avatarUrl: "https://randomuser.me/api/portraits/men/15.jpg",
    location: "São Paulo, BR",
    email: "carlos.mendez@projectmatch.dev",
    phone: "+1 (555) 019-1102",
    linkedinHandle: "carlosmendez",
    githubHandle: "cmendez-fs",
  },
  {
    id: "c20",
    name: "Isabella Rossi",
    role: "Product Designer",
    skills: ["Sketch", "Motion prototyping", "Design systems", "Enterprise UX"],
    interests: ["B2B SaaS", "productivity tools", "fintech"],
    availability: "full-time",
    experience: "Mid",
    bio: "Designs complex enterprise workflows that still feel effortless.",
    avatarUrl: "https://randomuser.me/api/portraits/women/4.jpg",
    location: "Milan, IT",
    email: "isabella.rossi@projectmatch.dev",
    phone: "+1 (555) 019-2214",
    linkedinHandle: "isabellarossi",
  },
  {
    id: "c21",
    name: "Aditya Kapoor",
    role: "Backend Engineer",
    skills: ["Java", "Spring Boot", "Microservices", "Redis", "PostgreSQL"],
    interests: ["fintech", "scalability", "developer tools"],
    availability: "full-time",
    experience: "Senior",
    bio: "Builds backend services that handle traffic spikes without breaking a sweat.",
    avatarUrl: "https://randomuser.me/api/portraits/men/27.jpg",
    location: "Bengaluru, IN",
    email: "aditya.kapoor@projectmatch.dev",
    phone: "+1 (555) 019-3327",
    linkedinHandle: "adityakapoor",
    githubHandle: "akapoor-be",
  },
  {
    id: "c22",
    name: "Chloe Martin",
    role: "Growth Marketer",
    skills: ["Paid acquisition", "Performance marketing", "Funnel optimization", "Attribution"],
    interests: ["consumer growth", "e-commerce", "mobile apps"],
    availability: "20hrs/wk",
    experience: "Mid",
    bio: "Turns ad spend into predictable, repeatable growth.",
    avatarUrl: "https://randomuser.me/api/portraits/women/17.jpg",
    location: "Paris, FR",
    email: "chloe.martin@projectmatch.dev",
    phone: "+1 (555) 019-4438",
    linkedinHandle: "chloemartin",
  },
  {
    id: "c23",
    name: "Noah Bennett",
    role: "Mobile Engineer",
    skills: ["Flutter", "Dart", "Firebase", "Mobile performance"],
    interests: ["consumer apps", "health & fitness", "education"],
    availability: "full-time",
    experience: "Mid",
    bio: "Ships cross-platform apps that feel native on both iOS and Android.",
    avatarUrl: "https://randomuser.me/api/portraits/men/38.jpg",
    location: "Toronto, CA",
    email: "noah.bennett@projectmatch.dev",
    phone: "+1 (555) 019-5541",
    linkedinHandle: "noahbennett",
    githubHandle: "nbennett-flutter",
  },
  {
    id: "c24",
    name: "Aaliyah Johnson",
    role: "Data Scientist",
    skills: ["Time series forecasting", "R", "Python", "Causal inference"],
    interests: ["logistics", "climate", "retail"],
    availability: "full-time",
    experience: "Senior",
    bio: "Builds forecasting models teams actually trust and use.",
    avatarUrl: "https://randomuser.me/api/portraits/women/29.jpg",
    location: "Atlanta, GA",
    email: "aaliyah.johnson@projectmatch.dev",
    phone: "+1 (555) 019-6652",
    linkedinHandle: "aaliyahjohnson",
    githubHandle: "ajohnson-ds",
  },
  {
    id: "c25",
    name: "Daniel Cohen",
    role: "Product Manager",
    skills: ["Growth strategy", "Experimentation", "User onboarding", "Prioritization"],
    interests: ["consumer apps", "creator economy", "marketplaces"],
    availability: "full-time",
    experience: "Mid",
    bio: "Obsesses over activation and retention curves, not vanity metrics.",
    avatarUrl: "https://randomuser.me/api/portraits/men/45.jpg",
    location: "Tel Aviv, IL",
    email: "daniel.cohen@projectmatch.dev",
    phone: "+1 (555) 019-7763",
    linkedinHandle: "danielcohen",
  },
  {
    id: "c26",
    name: "Mei Lin",
    role: "Frontend Engineer",
    skills: ["Vue.js", "Svelte", "Web performance", "TypeScript"],
    interests: ["developer tools", "design engineering", "open source"],
    availability: "20hrs/wk",
    experience: "Mid",
    bio: "Chases every extra millisecond out of first paint.",
    avatarUrl: "https://randomuser.me/api/portraits/women/42.jpg",
    location: "Taipei, TW",
    email: "mei.lin@projectmatch.dev",
    phone: "+1 (555) 019-8874",
    linkedinHandle: "meilin",
    githubHandle: "mlin-fe",
  },
  {
    id: "c27",
    name: "Lukas Becker",
    role: "DevOps / SRE",
    skills: ["GCP", "Kubernetes", "Incident response", "Helm"],
    interests: ["reliability", "developer tools", "cost optimization"],
    availability: "full-time",
    experience: "Senior",
    bio: "Writes the runbook before the incident happens, not after.",
    avatarUrl: "https://randomuser.me/api/portraits/men/59.jpg",
    location: "Munich, DE",
    email: "lukas.becker@projectmatch.dev",
    phone: "+1 (555) 019-9985",
    linkedinHandle: "lukasbecker",
    githubHandle: "lbecker-sre",
  },
  {
    id: "c28",
    name: "Zainab Hussain",
    role: "UX Researcher",
    skills: ["Quantitative research", "Analytics", "A/B testing", "Journey mapping"],
    interests: ["fintech", "e-commerce", "accessibility"],
    availability: "10hrs/wk",
    experience: "Senior",
    bio: "Pairs behavioral data with user interviews to find the real story.",
    avatarUrl: "https://randomuser.me/api/portraits/women/58.jpg",
    location: "Karachi, PK",
    email: "zainab.hussain@projectmatch.dev",
    phone: "+1 (555) 019-1096",
    linkedinHandle: "zainabhussain",
  },
  {
    id: "c29",
    name: "Viktor Ivanov",
    role: "Security Engineer",
    skills: ["Cloud security", "SOC 2", "GDPR compliance", "Identity management"],
    interests: ["fintech", "healthtech", "privacy"],
    availability: "10hrs/wk",
    experience: "Senior",
    bio: "Gets startups audit-ready without slowing down shipping.",
    avatarUrl: "https://randomuser.me/api/portraits/men/67.jpg",
    location: "Sofia, BG",
    email: "viktor.ivanov@projectmatch.dev",
    phone: "+1 (555) 019-1207",
    linkedinHandle: "viktorivanov",
    githubHandle: "vivanov-sec",
  },
  {
    id: "c30",
    name: "Marco Silva",
    role: "Game Developer",
    skills: ["Unreal Engine", "C++", "Multiplayer networking", "Shaders"],
    interests: ["gaming", "AR/VR", "interactive media"],
    availability: "full-time",
    experience: "Senior",
    bio: "Ships multiplayer games that stay smooth under real player load.",
    avatarUrl: "https://randomuser.me/api/portraits/men/71.jpg",
    location: "Lisbon, PT",
    email: "marco.silva@projectmatch.dev",
    phone: "+1 (555) 019-1318",
    linkedinHandle: "marcosilva",
    githubHandle: "msilva-game",
  },
  {
    id: "c31",
    name: "Sara Nilsson",
    role: "Founding Engineer",
    skills: ["Full-stack", "Infra-as-code", "Product sense", "0-to-1 shipping"],
    interests: ["climate tech", "developer tools", "0-to-1 products"],
    availability: "full-time",
    experience: "Lead",
    bio: "Sets up the infra and ships the MVP in the same week.",
    avatarUrl: "https://randomuser.me/api/portraits/women/63.jpg",
    location: "Copenhagen, DK",
    email: "sara.nilsson@projectmatch.dev",
    phone: "+1 (555) 019-1429",
    linkedinHandle: "saranilsson",
    githubHandle: "snilsson-eng",
  },
  {
    id: "c32",
    name: "Ben Okonkwo",
    role: "Data Engineer",
    skills: ["Kafka", "Flink", "Streaming pipelines", "Python"],
    interests: ["fintech", "logistics", "real-time analytics"],
    availability: "full-time",
    experience: "Mid",
    bio: "Builds pipelines that process events in seconds, not overnight batches.",
    avatarUrl: "https://randomuser.me/api/portraits/men/84.jpg",
    location: "Lagos, NG",
    email: "ben.okonkwo@projectmatch.dev",
    phone: "+1 (555) 019-1530",
    linkedinHandle: "benokonkwo",
    githubHandle: "bokonkwo-data",
  },
  {
    id: "c33",
    name: "Lena Schmidt",
    role: "Brand & Visual Designer",
    skills: ["Illustration", "Packaging design", "Print design", "Typography"],
    interests: ["consumer brands", "sustainability", "retail"],
    availability: "10hrs/wk",
    experience: "Mid",
    bio: "Designs brand worlds that feel just as good on a box as on a screen.",
    avatarUrl: "https://randomuser.me/api/portraits/women/71.jpg",
    location: "Hamburg, DE",
    email: "lena.schmidt@projectmatch.dev",
    phone: "+1 (555) 019-1641",
    linkedinHandle: "lenaschmidt",
  },
  {
    id: "c34",
    name: "Jamal Carter",
    role: "Customer & Community Lead",
    skills: ["Community events", "Partnerships", "Ambassador programs", "Social media"],
    interests: ["creator economy", "gaming", "education"],
    availability: "20hrs/wk",
    experience: "Mid",
    bio: "Turns a Discord server into a movement people show up for.",
    avatarUrl: "https://randomuser.me/api/portraits/men/92.jpg",
    location: "Houston, TX",
    email: "jamal.carter@projectmatch.dev",
    phone: "+1 (555) 019-1752",
    linkedinHandle: "jamalcarter",
  },
];
